version: 2.1
workflows:
  main:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
        environment:
          GOFLAGS: -mod=vendor
    steps:
      - checkout
      - run: go test ./internal/logmessage/
  release:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
